# Generated by Django 4.1.6 on 2023-08-16 07:32

import django.core.validators
from django.db import migrations, models
import eventer.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[eventer.app.models.validate_date_not_in_past])),
                ('event_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[eventer.app.models.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[eventer.app.models.validate_password_contains_digit, django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
